### ISSUE TITLE
File Search is not compatible with new version of ULauncher

### ISSUE THREAD

**Issue by papermache** [brpaz/ulauncher-file-search#12]
Linux version: Linux 4.15.0-48-generic 
ULauncher v5.3.0~beta1 
Extension API v2.0.0 

![image](https://user-images.githubusercontent.com/2126012/59810911-77604d00-92d5-11e9-9080-4c1b77f20199.png)

**Comment by brpaz** [comment]
I plan to migrate all my extensions to the new version. I have done that yesterday for a couple of them. This one, probably on the next batch.

In the meanwhile, PRs are welcome.

**Comment by brpaz** [comment]
Its updated to the new version ;)

**Comment by papermache** [comment]
> Its updated to the new version ;)

Thanks!
