### ISSUE TITLE
Condition for determining file vs folder is unsafe

### ISSUE THREAD

**Issue by friday** [brpaz/ulauncher-file-search#7]
Many files don't have extensions (and some folders contain dots).

**Comment by brpaz** [comment]
Yes, I know. I just didn't want to call a function on each result to check if its a folder or not, just for the sake of displaying an icon, so I accepted it would be wrong in same cases.

But I am open for suggestions to improve.

**Comment by friday** [comment]
I suspected this was the reason. Considering Ulauncher will only show a very small set of results (since there's no scrollbar), I wouldn't be surprised if this had a negligible performance effect if you limit the results though.

Running multiple subprocesses may have a performance effect, but this should work:

```sh
RESULT_LIST="$HOME/Dropbox/
$HOME/.bashrc/
$HOME/Desktop/"
echo $RESULT_LIST | xargs ls -d1 2>/dev/null
```

Obviously you would have to create RESULT_LIST dynamically in python (adding `/` to every result). Since `.bashrc/` isn't valid, it will be filtered out, while the others won't be. Then you can use the output to determine. If a result entry + "/" is in the list, it's a directory.

I guess an even easier way would be to run two searches and concatenate the results, but this would change the order of the results, may not work with symlinks and likely affects the performance too.

**Comment by brpaz** [comment]
When migrating to the new API I changed this behavior. It now uses the Python built in functions to detect if its a file or folder.

**Comment by friday** [comment]
That's actually not safe either I think. In case it's the API I think it is it guesses based on the name.

Edit:
Yeah it's `guess_type`, which is based on the name. It's better anyway. And fast.
